version: '3'
services:

  influx1:
    image: influxdb:alpine
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecret
      - INFLUXDB_DB=forecasts
    ## uncomment to store the data outside the container
    #volumes:
    #  - ./influxdata:/var/lib/influxdb

  grib2influx:
    build: ../
    ports:
      - 8080:8080
    depends_on:
      - influx1


  grafana1:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-datasource.yaml:/usr/share/grafana/conf/datasources/influxdb.yaml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influx1
      